name: Build and Export to docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build and Export to docs
        run: npm run export

      - name: Commit and Push docs folder
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mv docs ../docs-temp
          git fetch origin gh-pages || true
          git switch --orphan gh-pages
          git rm -rf .
          cp -r ../docs-temp/* .
          rm -rf ../docs-temp
          git add .
          git commit -m "Deploy to GitHub Pages [skip ci]" || echo "No changes to commit"
          git push --force https://x-access-token:${PAT_TOKEN}@github.com/nishant-iith/ubuntu-portfolio.git gh-pages
